#!/bin/sh

# Commit Message Hook
#
# References:
#
# - https://typicode.github.io/husky/?id=husky_git_params-ie-commitlint-#/?id=husky_git_params-ie-commitlint-

yarn build
yarn check:types:build
yarn commitlint --edit $1
